### ISSUE TITLE
Errors with ES6 syntax when running Cannon

### ISSUE THREAD

**Issue by kieranajp** [jackfranklin/cannon-blog#1]
Hey,

Followed the instructions to set up and init cannon and that worked just fine, but unfortunately I'm not able to run the generated index.js file. The errors I'm getting are to do with ES6 syntax, but I've not really looked into how Babel works so it might be my fault :)

Here is a whole bunch of terminal spam (sorry!)

```
kieran@Rush:~/s/p/cannon
➤ node_modules/.bin/cannon-init
...<snip>... (all worked ok)

kieran@Rush:~/s/p/cannon
➤ node index.js

/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/lib/pages.js:1
(function (exports, require, module, __filename, __dirname) { import _ from 'l
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:171:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/cannon.js:4:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

kieran@Rush:~/s/p/cannon
➤ node -v
v0.10.30

kieran@Rush:~/s/p/cannon
➤ nvm use stable
Now using node v0.12.2

kieran@Rush:~/s/p/cannon
➤ node index.js
/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/lib/pages.js:1
(function (exports, require, module, __filename, __dirname) { import _ from 'l
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:171:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/cannon.js:4:10)
    at Module._compile (module.js:460:26)

kieran@Rush:~/s/p/cannon
➤ nvm use iojs
Now using io.js v2.2.1

kieran@Rush:~/s/p/cannon
➤ node index.js
/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/lib/pages.js:1
(function (exports, require, module, __filename, __dirname) { import _ from 'l
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:409:25)
    at Module._extensions..js (module.js:444:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:171:7)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/cannon.js:4:10)
    at Module._compile (module.js:426:26)

kieran@Rush:~/s/p/cannon
➤ subl .

kieran@Rush:~/s/p/cannon
➤ babel-node index.js
/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/node_modules/babel/node_modules/babel-core/lib/babel/polyfill.js:8
  throw new Error("only one instance of babel/polyfill is allowed");
        ^
Error: only one instance of babel/polyfill is allowed
    at Object.<anonymous> (/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/node_modules/babel/node_modules/babel-core/lib/babel/polyfill.js:8:9)
    at Module._compile (module.js:426:26)
    at Module._extensions..js (module.js:444:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kieran/.nvm/versions/io.js/v2.2.1/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:171:7)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node-polyfill.js:7:1)
    at Module._compile (module.js:426:26)
```

**Comment by jackfranklin** [comment]
This is definitely related to the fact that I've only ever used this module by `npm link cannon-blog` rather than `npm install cannon-blog`. I expect that the former means that transpiling through Babel works and the later doesn't. I'm surprised though, I would expect it to "just work". Thanks, I'll dig into it.

**Comment by jackfranklin** [comment]
Yup, running this locally I get the exact issue. Thanks :+1:

**Comment by jackfranklin** [comment]
@kieranajp could you try installing off the branch from this PR? https://github.com/jackfranklin/cannon-blog/pull/2

`npm install --save jackfranklin/cannon-blog#publishing-as-es5`

**Comment by jackfranklin** [comment]
I've just run that branch against my test blog locally and it holds up. Let me know how you get on.

EDIT: no I don't think it did - doing some more debugging.

**Comment by jackfranklin** [comment]
`cannon-blog@0.0.5` fixes.

**Comment by kieranajp** [comment]
Thanks @jackfranklin, that solved that one. Now though, the server starts successfully: 

```
kieran@Rush:~/s/p/cannon
➤ node index.js
Server running on localhost:8123
```

...but when I visit that URL I get an `ERR_EMPTY_RESPONSE` in Chrome, and the following in terminal:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'cannon-blog/component'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kieran/sites/playground/cannon/pages/index.js:1:26)
    at Module._compile (module.js:456:26)
    at normalLoader (/Users/kieran/sites/playground/cannon/node_modules/babel-core/lib/babel/api/register/node.js:150:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kieran/sites/playground/cannon/node_modules/babel-core/lib/babel/api/register/node.js:163:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Want me to open a new issue or keep it to this one?

**Comment by jackfranklin** [comment]
Ah sorry, it would have helped if I had told you the fix. Now the module gets published having already been run through Babel, a side effect being that some components have moved. You need to change every: `cannon-blog/X`  import to `cannon-blog/lib/X` import.

Sorry - docs dreadfully lacking right now, I know! Keep asking questions though, happy to help :)

**Comment by kieranajp** [comment]
Hey Jack,

Sorry it's been a few days, but I've finally had a chance to look at this.

In short, it seems to be working okay, but obviously I'm now at the stage of working out how to create new posts etc.

However I did have to create a favicon (oh noes!)

Here's my terminal output for reference, because there were some warnings and stuff that might be useful for you (also it was pretty slow on initial load):

```
kieran@Rush:~/s/p/cannon
➤ node index.js
Server running on localhost:8123
Generating client side bundle
[BABEL] Note: The code generator has deoptimised the styling of "/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/node_modules/lodash/index.js" as it exceeds the max of "100KB".
Generating client side bundle
[BABEL] Note: The code generator has deoptimised the styling of "/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/node_modules/lodash/index.js" as it exceeds the max of "100KB".
Webpack Bundle Generated
Errors? false
Warnings? false
Server route /
Server route /2015-05-31-hello-world/
Webpack Bundle Generated
Errors? false
Warnings? false
Server route /
Server route /2015-05-31-hello-world/
Generating client side bundle
[BABEL] Note: The code generator has deoptimised the styling of "/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/node_modules/lodash/index.js" as it exceeds the max of "100KB".
Webpack Bundle Generated
Errors? false
Warnings? false
Server route /
Server route /2015-05-31-hello-world/
Warning: No route matches path "/favicon.ico/". Make sure you have <Route path="/favicon.ico/"> somewhere in your routes

/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/lib/render.js:87
        var matchedLayout = matchedRoute.meta.layout || 'default';
                                        ^
TypeError: Cannot read property 'meta' of undefined
    at Function.<anonymous> (/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/lib/render.js:87:41)
    at Function.dispatchHandler (/Users/kieran/sites/playground/cannon/node_modules/react-router/lib/createRouter.js:381:22)
    at /Users/kieran/sites/playground/cannon/node_modules/react-router/lib/createRouter.js:349:29
    at Function.Transition.to (/Users/kieran/sites/playground/cannon/node_modules/react-router/lib/Transition.js:72:15)
    at /Users/kieran/sites/playground/cannon/node_modules/react-router/lib/createRouter.js:348:22
    at Function.Transition.from (/Users/kieran/sites/playground/cannon/node_modules/react-router/lib/Transition.js:51:15)
    at Function.dispatch (/Users/kieran/sites/playground/cannon/node_modules/react-router/lib/createRouter.js:345:20)
    at Function.refresh (/Users/kieran/sites/playground/cannon/node_modules/react-router/lib/createRouter.js:396:16)
    at Function.run (/Users/kieran/sites/playground/cannon/node_modules/react-router/lib/createRouter.js:392:16)
    at /Users/kieran/sites/playground/cannon/node_modules/cannon-blog/lib/render.js:85:14

kieran@Rush:~/s/p/cannon
➤ touch public/favicon.ico

kieran@Rush:~/s/p/cannon
➤ node index.js
Server running on localhost:8123
Generating client side bundle
[BABEL] Note: The code generator has deoptimised the styling of "/Users/kieran/sites/playground/cannon/node_modules/cannon-blog/node_modules/lodash/index.js" as it exceeds the max of "100KB".
Webpack Bundle Generated
Errors? false
Warnings? false
Server route /
Server route /2015-05-31-hello-world/
```

**Comment by jackfranklin** [comment]
Yeah, you're basically hitting the fact that it's not ready for production yet! It regens the client side bundle on each request, and what I need to do instead is swap to the webpack dev server. It needs to handle 404s better and the output generally needs to be cleaner.

**Comment by kieranajp** [comment]
No worries mate! I can tinker with it from here and see how far I get. May be a couple of weeks before I get anywhere because my evenings are inundated with freelance work atm, but I'll get back to you either a) with a PR for documentation because I've got it working or b) with questions :p

**Comment by kieranajp** [comment]
IT'S WORKING!!!! And it's FAST!
